### ISSUE TITLE
message from Rafi / IRremote repo Down!

### ISSUE THREAD

**Issue by AnalysIR** [bengtmartensson/AGirs#26]
Hi. (From rafi, relayed as requested)

I just wanted to inform you that my account has temporarily been flagged on github. Probably got stuck in some random spam filter bot.

I submitted a ticket to GitHub but it may take a while to fix.

In the meantime the repo is inaccessible, any chance you could somehow post an issue on one of bengtmartenssons's repos just to let him know?

Your email is the only one I have from the community.

Thanks,
Rafi Khan

**Comment by bengtmartensson** [comment]
Problem has been resolved. Closing.
