### ISSUE TITLE
Wrong #ifndef in file girs_pins_nano_shield.h

### ISSUE THREAD

**Issue by gklement** [bengtmartensson/AGirs#35]
Drop file from repos or change
#ifndef GIRS_PINS_NANO_H
#define GIRS_PINS_NANO_H
into
#ifndef GIRS_PINS_NANO_SHIELD_H
#define GIRS_PINS_NANO_SHIELD_H

but values will still depend on include order.

**Comment by bengtmartensson** [comment]
Thank you very much for the observation. Actually, these files (`girs_pins_*.h`) are not headers in the strict sense, so include guards in the traditional sense do not really make sense here, although I agree that it is currently quite confusing. I have instead opened the more general issue #36, that addresses this and other problems. Your feedback and other contributions are most welcome there.

**Comment by bengtmartensson** [comment]
This project is now using #pragma once instead of the legacy include guards.
