### ISSUE TITLE
Rename *_VSS variables

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/AGirs#47]
Vss is not considered as a good notation for a positive supply voltage.
https://en.wikipedia.org/wiki/IC_power-supply_pin 
(However, an accepted authoritative  standard does not seem to exist, only "conventions".)

Suggested by Daniel Ford in a private message.

**Comment by DanielTheGreat** [comment]
It's likely that many IR sensors use bipolar transistor technology, so I suggest Vcc would be the most appropriate name for the positive rail.  (See block diagrams in attachments for examples.)
[QSE156-159_IR_sensors(Fairchild).pdf](https://github.com/bengtmartensson/AGirs/files/3325659/QSE156-159_IR_sensors.Fairchild.pdf)
[NJL73H400A_IR_Rx.pdf](https://github.com/bengtmartensson/AGirs/files/3325661/NJL73H400A_IR_Rx.pdf)
Daniel
